
GET http://localhost:5281/api/mdUsers HTTP/1.1

###
GET http://localhost:5281/api/mdUsers/1 HTTP/1.1

###
GET http://localhost:5281/api/mdUsers/2 HTTP/1.1

###
GET http://localhost:5281/api/mdUsers/10002 HTTP/1.1

###
PUT http://localhost:5281/api/mdUsers/10002 HTTP/1.1
content-type: application/json

{   
    "id": 10002,
    "login": "test",
    "password": "testpasswd"
}

###
DELETE http://localhost:5281/api/mdUsers/20005 HTTP/1.1

###
POST http://localhost:5281/api/mdUsers HTTP/1.1
content-type: application/json

{
    "login": "MD_Maciej",
    "password": "MdMaciej1$%2"
}

###
POST http://localhost:5281/api/mdUsers HTTP/1.1
content-type: application/json

{
    "login": "MD_Daria",
    "password": "MdDaria1$%2"
}

###
POST http://localhost:5281/api/mdUsers HTTP/1.1
content-type: application/json

{
    "login": "Test4",
    "password": "HasloTest5"
}